Repository wecode-bootcamp-korea/39-2nd-bZrunch-frontend, pull requests merged in 2022-12, with the labels that each got.

#2 [39기 김보윤] ADD: 로그인 레이아웃 완성
  package-lock.json
  package.json
  public/images/kimboyoon/채소사진.jpg
  src/pages/Login/Login.js
  src/pages/Login/Slide.js
Labels: 멘토 리뷰 요청

#5 [39기 김건우] ADD: Cart 레이아웃 완료
  public/images/Cart/cat.jpg
  src/pages/Cart/Cart.js
Labels: 멘토 리뷰 요청

#9 [39기 김보윤] ADD: nav layout 완성
  src/components/Nav/LeftNav.js
  src/components/Nav/Nav.js
Labels: 멘토 리뷰 요청

#16 [39기 김보윤] ADD: ListArticle 기능 + 메인페이지에서 category 클릭시 이동하는 것 까지
  src/Router.js
  src/components/ScrollToTop.js
  src/index.js
  src/pages/ArticleList/ArticleList.js
  src/pages/ArticleList/ListBox.js
  src/pages/Main/KeywordList.js
  src/pages/Main/MainSlide.js
Labels: 멘토 리뷰 요청

#12 [39기 이유주] Feature/search 검색 기능 구현 완료
  public/data/search.json
  public/images/Search/boyoon.png
  public/images/Search/dongkeun.jpeg
  public/images/Search/hyunsang.png
  public/images/Search/kunwoo.png
  public/images/Search/photo2.jpeg
  src/pages/Search/Search.js
Labels: 수정 요청

#18 [39기 김건우] 글쓰기 페이지 기능 구현중
  package-lock.json
  package.json
  public/images/Write/changecolor.png
  public/images/Write/insertimg.png
  src/components/Footer/Footer.js
  src/pages/Write/ColorSlide.js
  src/pages/Write/Write.js
  src/styles/theme.js
Labels: 추가 기능 구현 중

#14 [39기 김보윤] ADD: cart 기능 구현
  package.json
  src/Router.js
  src/pages/Cart/Cart.js
  src/pages/Cart/KakaoPay.js
  src/pages/Cart/KakaoPayFail.js
Labels: Conflict 해결 요청
